#!/usr/bin/env python
"""
Generate lux configuration files (.ini) for ray-tracing pre-projected lens planes.

This creates configuration files for the lux ray-tracing code to read
pre-computed density maps from generate_lensplanes.py.

Usage:
    python scripts/generate_lux_configs.py --sim-res 625 --model all
    python scripts/generate_lux_configs.py --sim-res 2500 --model replace --mass-min 12.5
"""

import os
import argparse
from pathlib import Path

# Snapshot configuration (must match generate_lensplanes.py)
SNAPSHOT_CONFIG = [
    (96, 0.04, False),
    (90, 0.15, False),
    (85, 0.27, False),
    (80, 0.40, False),
    (76, 0.50, False),
    (71, 0.64, False),
    (67, 0.78, False),
    (63, 0.93, False),
    (59, 1.07, False),
    (56, 1.18, False),
    (52, 1.36, True),
    (49, 1.50, True),
    (46, 1.65, True),
    (43, 1.82, True),
    (41, 1.93, True),
    (38, 2.12, True),
    (35, 2.32, True),
    (33, 2.49, True),
    (31, 2.68, True),
    (29, 2.87, True),
]

CONFIG_TEMPLATE = """# Lux configuration for {model_name}
# Auto-generated by generate_lux_configs.py
# Simulation: L205n{sim_res}TNG

# Input: Pre-projected density maps
input_dir = {input_dir}

# Output directories
LP_output_dir = {lp_output_dir}
RT_output_dir = {rt_output_dir}

# Simulation format
simulation_format = PreProjected

# Lens plane configuration
LP_grid = {lp_grid}
planes_per_snapshot = {pps}
projection_direction = -1
translation_rotation = false
LP_random_seed = {seed}

# Ray-tracing configuration
RT_grid = {rt_grid}
RT_random_seed = 1992
RT_randomization = true

# Field of view
angle = {angle}

# Snapshot configuration
snapshot_list = {snap_list}
snapshot_stack = {stack_list}

# Verbosity
verbose = true
"""


def generate_config(sim_res, model_name, mass_label, lp_grid=4096, rt_grid=1024,
                   angle=5.0, pps=2, seed=2020, output_base=None, lux_out_base=None):
    """
    Generate lux configuration file for a specific model.
    
    Parameters
    ----------
    sim_res : int
        Simulation resolution (625, 1250, 2500)
    model_name : str
        Model name (dmo, hydro, replace, bcm_arico20, etc.)
    mass_label : str
        Mass cut label (e.g., "Mgt12.5" or "M12.0-12.5")
    lp_grid : int
        Lens plane grid resolution
    rt_grid : int
        Ray-tracing grid resolution
    angle : float
        Field of view in degrees
    pps : int
        Planes per snapshot
    seed : int
        Random seed
    output_base : str
        Base directory for pre-projected maps
    lux_out_base : str
        Base directory for lux outputs
    
    Returns
    -------
    config_str : str
        Configuration file contents
    config_path : str
        Path to save configuration
    """
    if output_base is None:
        output_base = '/mnt/home/mlee1/ceph/hydro_replace_lensplanes'
    if lux_out_base is None:
        lux_out_base = '/mnt/home/mlee1/ceph/lux_out'
    
    # Build paths
    sim_label = f'L205n{sim_res}TNG'
    
    # Model directory name (may include mass label for replace)
    if model_name == 'replace':
        model_dir = f'{model_name}_{mass_label}'
    else:
        model_dir = model_name
    
    input_dir = f'{output_base}/{sim_label}/{model_name}'
    lp_output_dir = f'{lux_out_base}/{sim_label}/{model_dir}/LP_output'
    rt_output_dir = f'{lux_out_base}/{sim_label}/{model_dir}/RT_output'
    
    # Build snapshot lists
    snap_list = ', '.join(str(s[0]) for s in SNAPSHOT_CONFIG)
    stack_list = ', '.join('true' if s[2] else 'false' for s in SNAPSHOT_CONFIG)
    
    # Generate config content
    config_str = CONFIG_TEMPLATE.format(
        model_name=model_name,
        sim_res=sim_res,
        input_dir=input_dir,
        lp_output_dir=lp_output_dir,
        rt_output_dir=rt_output_dir,
        lp_grid=lp_grid,
        pps=pps,
        seed=seed,
        rt_grid=rt_grid,
        angle=angle,
        snap_list=snap_list,
        stack_list=stack_list,
    )
    
    # Config file path
    config_dir = Path('/mnt/home/mlee1/hydro_replace2/config/lux')
    config_path = config_dir / f'lux_{sim_label}_{model_dir}.ini'
    
    return config_str, str(config_path)


def main():
    parser = argparse.ArgumentParser(description='Generate lux configuration files')
    parser.add_argument('--sim-res', type=int, default=625, choices=[625, 1250, 2500],
                       help='Simulation resolution')
    parser.add_argument('--model', type=str, default='all',
                       choices=['dmo', 'hydro', 'replace', 'bcm', 'all'],
                       help='Model(s) to generate configs for')
    parser.add_argument('--mass-min', type=float, nargs='+', default=[12.0, 12.5, 13.0],
                       help='Mass cuts for replace model (log10 Msun/h)')
    parser.add_argument('--lp-grid', type=int, default=4096,
                       help='Lens plane grid resolution')
    parser.add_argument('--rt-grid', type=int, default=1024,
                       help='Ray-tracing grid resolution')
    parser.add_argument('--angle', type=float, default=5.0,
                       help='Field of view (degrees)')
    parser.add_argument('--seed', type=int, default=2020,
                       help='Random seed')
    parser.add_argument('--dry-run', action='store_true',
                       help='Print configs without writing')
    
    args = parser.parse_args()
    
    # Create config directory
    config_dir = Path('/mnt/home/mlee1/hydro_replace2/config/lux')
    config_dir.mkdir(parents=True, exist_ok=True)
    
    # Build list of models to process
    models = []
    if args.model == 'all':
        models = ['dmo', 'hydro']
        models.extend([f'replace' for _ in args.mass_min])
        models.extend(['bcm_arico20', 'bcm_schneider19', 'bcm_schneider25'])
    elif args.model == 'bcm':
        models = ['bcm_arico20', 'bcm_schneider19', 'bcm_schneider25']
    elif args.model == 'replace':
        models = ['replace'] * len(args.mass_min)
    else:
        models = [args.model]
    
    print(f"Generating lux configs for L205n{args.sim_res}TNG")
    print(f"Models: {set(models)}")
    print()
    
    # Generate configs
    mass_idx = 0
    for model in models:
        if model == 'replace':
            mass_min = args.mass_min[mass_idx]
            mass_label = f'Mgt{mass_min:.1f}'
            mass_idx += 1
        else:
            mass_label = ''
        
        config_str, config_path = generate_config(
            sim_res=args.sim_res,
            model_name=model,
            mass_label=mass_label,
            lp_grid=args.lp_grid,
            rt_grid=args.rt_grid,
            angle=args.angle,
            seed=args.seed,
        )
        
        if args.dry_run:
            print(f"=== {config_path} ===")
            print(config_str)
            print()
        else:
            with open(config_path, 'w') as f:
                f.write(config_str)
            print(f"Wrote: {config_path}")
    
    print()
    print("Done!")


if __name__ == '__main__':
    main()
