#!/bin/bash
#SBATCH --job-name=unified_missing
#SBATCH --output=logs/unified_missing_%A_%a.o
#SBATCH --error=logs/unified_missing_%A_%a.e
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --time=12:00:00
#SBATCH --partition=cca
#SBATCH --mem=0
#SBATCH --array=0-4,6,8-12,14-17,19

# =============================================================================
# Targeted re-run of unified pipeline for MISSING lensplanes only
# =============================================================================
#
# This script re-runs the unified pipeline for specific snapshots that had
# incomplete lens plane generation due to OOM errors.
#
# Changes from original run_unified_2500_array.sh:
#   - #SBATCH --mem=0        : Use ALL available memory per node
#   - --nodes=4              : Fewer nodes but more memory per task
#   - --ntasks-per-node=1    : One task per node to maximize memory
#   - --cpus-per-task=16     : More CPUs for parallelism within task
#
# Missing snapshots: 0-4,6,8-12,14-17,19 (16 total)
# Generated by: find_missing_lensplanes.py
#
# NOTE: We do NOT use --incremental because the incremental check only looks
# at LP_00. If LP_00 exists but other LPs are missing, it would skip the
# entire config. Instead, we let it regenerate all configs for this snapshot.
# The generation is idempotent (same random transforms used).
#
# =============================================================================

module purge
module load python openmpi python-mpi hdf5
source /mnt/home/mlee1/venvs/hydro_replace/bin/activate

cd /mnt/home/mlee1/hydro_replace2

# Map array index to snapshot number
SNAPSHOTS=(96 90 85 80 76 71 67 63 59 56 52 49 46 43 41 38 35 33 31 29)
SNAP=${SNAPSHOTS[$SLURM_ARRAY_TASK_ID]}

# Calculate lenspot file indices for this snapshot
# lenspot index = snapshot_idx * planes_per_snapshot + pps_slice
# With pps=2: snapshot 0 -> lenspot00,01; snapshot 1 -> lenspot02,03; etc
PPS=2
LENSPOT_START=$((SLURM_ARRAY_TASK_ID * PPS))
LENSPOT_END=$((LENSPOT_START + PPS - 1))

echo "========================================"
echo "Unified Pipeline - Missing Lensplanes Re-run"
echo "Resolution: 2500"
echo "Array task: $SLURM_ARRAY_TASK_ID"
echo "Snapshot: $SNAP"
echo "Lenspot files: lenspot${LENSPOT_START} - lenspot${LENSPOT_END}"
echo "Nodes: $SLURM_NNODES"
echo "Tasks: $SLURM_NTASKS"
echo "CPUs per task: $SLURM_CPUS_PER_TASK"
echo "Memory: ALL (--mem=0)"
echo "========================================"

# Show memory info
echo ""
echo "Memory per node:"
free -h
echo ""

# List of models that have missing lensplanes for this snapshot
# (Generated by find_missing_lensplanes.py)
MODELS_WITH_MISSING=(
    "hydro_replace_Ml_1.00e12_Mu_3.16e12_R_0.5"
    "hydro_replace_Ml_1.00e12_Mu_inf_R_3.0"
    "hydro_replace_Ml_1.00e12_Mu_inf_R_5.0"
    "hydro_replace_Ml_1.00e13_Mu_3.16e13_R_1.0"
    "hydro_replace_Ml_1.00e13_Mu_inf_R_0.5"
    "hydro_replace_Ml_1.00e13_Mu_inf_R_1.0"
    "hydro_replace_Ml_1.00e13_Mu_inf_R_5.0"
    "hydro_replace_Ml_3.16e12_Mu_1.00e13_R_0.5"
    "hydro_replace_Ml_3.16e12_Mu_1.00e13_R_1.0"
    "hydro_replace_Ml_3.16e12_Mu_inf_R_1.0"
    "hydro_replace_Ml_3.16e12_Mu_inf_R_3.0"
    "hydro_replace_Ml_3.16e12_Mu_inf_R_5.0"
    "hydro_replace_Ml_3.16e13_Mu_1.00e15_R_5.0"
)

# Check which models actually need re-running for this snapshot
LP_BASE="/mnt/home/mlee1/ceph/hydro_replace_LP/L205n2500TNG"
echo ""
echo "Checking which models need regeneration for snapshot $SNAP..."
for MODEL in "${MODELS_WITH_MISSING[@]}"; do
    MISSING=0
    for LP_ID in $(seq 0 9); do
        LP_DIR="$LP_BASE/$MODEL/LP_$(printf '%02d' $LP_ID)"
        for LIDX in $(seq $LENSPOT_START $LENSPOT_END); do
            LFILE="$LP_DIR/lenspot$(printf '%02d' $LIDX).dat"
            if [ ! -f "$LFILE" ]; then
                MISSING=$((MISSING + 1))
            fi
        done
    done
    if [ $MISSING -gt 0 ]; then
        echo "  $MODEL: $MISSING missing files"
    fi
done
echo ""

# Run unified pipeline with lensplane generation
# Key flags:
#   --phase5-only   : Skip phases 1-4, only generate lensplanes
#   --incremental   : Only regenerate configs with missing files (now checks ALL LPs)
srun python3 -u scripts/generate_all_unified.py \
    --snap $SNAP \
    --sim-res 2500 \
    --mass-min 12.0 \
    --radius-mult 5.0 \
    --grid 1024 \
    --enable-lensplanes \
    --lensplane-grid 4096 \
    --phase5-only \
    --incremental

echo ""
echo "========================================"
echo "Snapshot $SNAP complete"
echo "========================================"
