#!/bin/bash
#SBATCH -p cca
#SBATCH --constraint=icelake
#SBATCH -J lux_2500
#SBATCH -n 64
#SBATCH -N 4
#SBATCH --exclusive
#SBATCH -o /mnt/home/mlee1/hydro_replace2/logs/lux_2500_%A_%a.o
#SBATCH -e /mnt/home/mlee1/hydro_replace2/logs/lux_2500_%A_%a.e
#SBATCH -t 24:00:00
#SBATCH --array=0-9

# ==============================================================================
# Run lux ray-tracing for L205n2500TNG after lens planes complete
#
# Array indices (matches lensplanes):
#   0: DMO
#   1: Hydro
#   2-5: Replace (mass thresholds 12.5, 13.0, 13.5, 14.0)
#   6-9: BCM-Arico20 (mass thresholds 12.5, 13.0, 13.5, 14.0)
#
# Submit with dependency:
#   sbatch --dependency=aftercorr:LENSPLANES_JOB batch/run_lux_2500.sh
# ==============================================================================

# Model configuration by array index
declare -a MODELS=("dmo" "hydro" "replace" "replace" "replace" "replace" "bcm" "bcm" "bcm" "bcm")
declare -a MASS_MINS=("12.5" "12.5" "12.5" "13.0" "13.5" "14.0" "12.5" "13.0" "13.5" "14.0")

MODEL=${MODELS[$SLURM_ARRAY_TASK_ID]}
MASS_MIN=${MASS_MINS[$SLURM_ARRAY_TASK_ID]}

SIM_RES=2500
LP_GRID=${LP_GRID:-4096}
RT_GRID=${RT_GRID:-1024}
SEED_START=${SEED_START:-2020}
NUM_SEEDS=${NUM_SEEDS:-20}

# Paths
LUX_DIR=/mnt/home/mlee1/lux
LENSPLANE_BASE=/mnt/home/mlee1/ceph/hydro_replace_lensplanes
LUX_OUTPUT=/mnt/home/mlee1/ceph/lux_out
SIM_NAME="L205n${SIM_RES}TNG"

# Setup environment
module purge
module load python openmpi python-mpi
module load hdf5 fftw gsl boost/mpi-1.84.0
source /mnt/home/mlee1/venvs/hydro_replace/bin/activate

cd /mnt/home/mlee1/hydro_replace2

echo "=============================================="
echo "Running lux ray-tracing for L205n${SIM_RES}TNG"
echo "Array task: $SLURM_ARRAY_TASK_ID"
echo "Model: $MODEL"
echo "Mass cut: M > 10^${MASS_MIN} Msun/h"
echo "LP Grid: $LP_GRID, RT Grid: $RT_GRID"
echo "Seeds: $SEED_START to $((SEED_START + NUM_SEEDS - 1)) ($NUM_SEEDS realizations)"
echo "=============================================="

# Determine model label for output
if [ "$MODEL" == "dmo" ] || [ "$MODEL" == "hydro" ]; then
    MODEL_LABEL="${MODEL}"
elif [ "$MODEL" == "replace" ]; then
    MODEL_LABEL="replace_Mgt${MASS_MIN}"
else
    MODEL_LABEL="bcm_arico20_Mgt${MASS_MIN}"
fi

# Snapshot configuration
SNAPSHOT_LIST="96,90,85,80,76,71,67,63,59,56,52,49,46,43,41,38,35,33,31,29"
SNAPSHOT_STACK="false,false,false,false,false,false,false,false,false,false,true,true,true,true,true,true,true,true,true,true"

# Loop over seeds
SEEDS_COMPLETED=0
SEEDS_SKIPPED=0

for ((SEED=$SEED_START; SEED<$SEED_START+$NUM_SEEDS; SEED++)); do
    echo ""
    echo "=============================================="
    echo "Processing seed ${SEED}"
    echo "=============================================="
    
    # Input directory with seed
    INPUT_DIR="${LENSPLANE_BASE}/${SIM_NAME}/seed${SEED}/${MODEL_LABEL}"
    
    # Output directories with seed
    LP_OUTPUT="${LUX_OUTPUT}/${SIM_NAME}/seed${SEED}/${MODEL_LABEL}/lenspot"
    RT_OUTPUT="${LUX_OUTPUT}/${SIM_NAME}/seed${SEED}/${MODEL_LABEL}/raytracing"
    
    mkdir -p "$LP_OUTPUT" "$RT_OUTPUT"
    
    echo "Input: $INPUT_DIR"
    echo "LP Output: $LP_OUTPUT"
    echo "RT Output: $RT_OUTPUT"
    
    # Check if input directory exists
    if [ ! -d "$INPUT_DIR" ]; then
        echo "WARNING: Input directory does not exist: $INPUT_DIR"
        echo "Skipping seed ${SEED}..."
        SEEDS_SKIPPED=$((SEEDS_SKIPPED + 1))
        continue
    fi
    
    # Check if lens plane files actually exist (expect ~40 files for 20 snapshots × 2 planes)
    LP_FILES=$(find "$INPUT_DIR" -name "density*.dat" 2>/dev/null | wc -l)
    if [ "$LP_FILES" -lt 20 ]; then
        echo "WARNING: Only found $LP_FILES density files in $INPUT_DIR (expected ~40)"
        echo "Skipping seed ${SEED} - lens planes may be incomplete"
        SEEDS_SKIPPED=$((SEEDS_SKIPPED + 1))
        continue
    fi
    echo "Found $LP_FILES lens plane files"
    
    # Generate lux config file
    CONFIG_FILE="${LUX_OUTPUT}/${SIM_NAME}/seed${SEED}/${MODEL_LABEL}/lux.ini"
    mkdir -p "$(dirname $CONFIG_FILE)"
    
    cat > "$CONFIG_FILE" << EOF
# Lux configuration for ${MODEL_LABEL} seed=${SEED}
# Auto-generated by run_lux_2500.sh

input_dir = ${INPUT_DIR}
LP_output_dir = ${LP_OUTPUT}
RT_output_dir = ${RT_OUTPUT}
simulation_format = PreProjected
LP_grid = ${LP_GRID}
RT_grid = ${RT_GRID}
planes_per_snapshot = 2
projection_direction = z
translation_rotation = true
LP_random_seed = ${SEED}
RT_random_seed = ${SEED}
RT_randomization = 100
angle = 5.0
verbose = true
snapshot_list = ${SNAPSHOT_LIST}
snapshot_stack = ${SNAPSHOT_STACK}
EOF

    echo "Generated config: $CONFIG_FILE"
    echo ""
    
    # Run lux lenspot phase
    echo ">>> Phase 1: Lens Potential (lenspot)"
    cd $LUX_DIR
    mpirun -np $SLURM_NTASKS ./lux lenspot "$CONFIG_FILE"
    LP_STATUS=$?
    
    if [ $LP_STATUS -ne 0 ]; then
        echo "ERROR: lenspot failed with status $LP_STATUS"
        continue
    fi
    
    # Run lux raytracing phase
    echo ""
    echo ">>> Phase 2: Ray-tracing"
    mpirun -np $SLURM_NTASKS ./lux raytracing "$CONFIG_FILE"
    RT_STATUS=$?
    
    if [ $RT_STATUS -ne 0 ]; then
        echo "ERROR: raytracing failed with status $RT_STATUS"
        continue
    fi
    
    echo ""
    echo "Completed seed ${SEED}"
    SEEDS_COMPLETED=$((SEEDS_COMPLETED + 1))
done

echo ""
echo "=============================================="
echo "Summary for $MODEL_LABEL:"
echo "  Seeds completed: $SEEDS_COMPLETED"
echo "  Seeds skipped: $SEEDS_SKIPPED"
echo "=============================================="
